name: ci 
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install weasyprint mkdocs-with-pdf qrcode mkdocs-material
      - run: mkdocs gh-deploy
